Feat/remove contribution
onlydustxyz/marketplace-smart-contracts pull request #74
Opened 2022-08-19 04:56 UTC by oxlime

This is what i have so far, my idea of removing by basically zero'ing out the contribution. I'm having issues with removing while also looping through the contributions.

2022-08-19 07:29 UTC, AnthonyBuisset requested changes
Nice ! Thanks for the contribution.

Could you please modify the e2e test as well ? Check `test_contributions.e2e.cairo` file.
It should show that a change is missing in the Interface as well.

I do not think there is a better way of doing it as it is not possible to delete storage in starknet AFAIK. Zero-ing all fields is the way to do.
Good work overall !

2022-08-19 07:29 UTC, AnthonyBuisset commented on contracts/onlydust/deathnote/core/contributions/test_contributions.cairo
> +
you can also check that if you try to read the deleted contribution, the call is reverted with "Contributions: Contribution does not exist"

2022-08-22 08:46 UTC, oxlime commented
Deleted contributions are still indexed but all values set to 0. So I reworked the fetch_contribution_loop to loop over contributions with contribution_id = 0.

2022-08-27 23:50 UTC, oxlime commented
closing this because i opened a new pr after the refactor

2022-08-27 23:50 UTC, closed without merging