add remove_contributions
onlydustxyz/marketplace-smart-contracts pull request #81
Opened 2022-08-27 23:45 UTC by oxlime

Started a new pr since the changed a lot refactor. Set contributions values to 0. Set the status to NONE not sure if it also should be 0. 

Will add more tests if this implementation looks good.

2022-08-27 23:49 UTC, oxlime commented
closes #69

2022-08-30 03:16 UTC, AnthonyBuisset requested changes
Good work, this is exactly what we had in mind. 
I added comments on remaining tasks

2022-08-30 03:16 UTC, AnthonyBuisset commented on contracts/onlydust/marketplace/core/contributions/library.cairo
> +    # Remove a contribution for a given token id
Not a token, you can however tall about `contribution_id` as this is part of our domain language

2022-08-30 03:16 UTC, AnthonyBuisset commented on contracts/onlydust/marketplace/core/contributions/library.cairo
> +func ContributionRemoved(contribution_id: felt):
I prefer to say Delete instead of Remove as this is more precise (we erase data and not just removing from a container)

2022-08-30 03:16 UTC, AnthonyBuisset commented on contracts/onlydust/marketplace/core/contributions/test_contributions.cairo
> +func test_contribution_can_be_removed{
Can you please add a test to check that only feeder can delete a contribution?

2022-08-30 03:16 UTC, AnthonyBuisset commented on contracts/onlydust/marketplace/core/contributions/library.cairo
> +        internal.only_feeder()
Let's also add a rule that only a contribution in OPEN status can be deleted
This will ensure we are not deleting a contribution that a contributor is currently working on

2022-08-30 06:40 UTC, oxlime commented
Think I got everything you requested @AnthonyBuisset let me know if theres more testing needed.

2022-08-30 08:57 UTC, AnthonyBuisset requested changes
Just a few minor comments and we should be good

2022-08-30 08:57 UTC, AnthonyBuisset commented on contracts/onlydust/marketplace/core/contributions/test_contributions.cairo
> +    let (contribution2) = contributions.new_contribution(1000000 * PROJECT_ID + 2, PROJECT_ID, 0)
only one call is required here

2022-08-30 08:57 UTC, AnthonyBuisset commented on contracts/onlydust/marketplace/core/contributions/test_contributions.cairo
> +    let (contribution2) = contributions.new_contribution(1000000 * PROJECT_ID + 2, PROJECT_ID, 0)
only one call is needed

2022-08-30 08:57 UTC, AnthonyBuisset commented on contracts/onlydust/marketplace/core/contributions/library.cairo
> +    # Remove a contribution for a given contribution_id
can you please change remove into delete in the comment as well ?

2022-08-30 08:57 UTC, AnthonyBuisset commented on contracts/onlydust/marketplace/core/contributions/test_contributions.cairo
> +    let (contribution2) = contributions.new_contribution(1000000 * PROJECT_ID + 2, PROJECT_ID, 0)
only one call as well

2022-08-30 09:24 UTC, oxlime commented
tell rascar im on to the next lol @AnthonyBuisset

2022-08-30 10:05 UTC, AnthonyBuisset approved these changes

2022-08-30 12:00 UTC, merged